<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<script>
			// 收集资源加载错误的方法
			window.addEventListener(
				"error",
				(errorEvent) => {
					if (
						errorEvent.srcElement.localName == "link" ||
						errorEvent.srcElement.localName == "script" ||
						errorEvent.srcElement.localName == "img"
					) {
						console.log(errorEvent.srcElement.localName + "资源加载失败......");
						console.log(errorEvent);
					}
					errorEvent.preventDefault();
				},
				true
			);

			// 收集全局错误的方法
			window.onerror = (msg, url, lineNum, colNum, err) => {
				console.log(`错误发生的异常信息（字符串）:${msg}`);
				console.log(`错误发生的脚本URL（字符串）:${url}`);
				console.log(`错误发生的行号（数字）:${lineNum}`);
				console.log(`错误发生的列号（数字）:${colNum}`);
				console.log(`错误发生的Error对象（错误对象）:${err}`);
			};

			// 收集promise错误的方法
			window.addEventListener("unhandledrejection", (e) => {
				console.log(
					`Promise.reject()中的内容，告诉你发生错误的原因:【${e.reason}】`
				);
				console.log(`Promise对象 :【${e.promise}】`);
			});

			// var a = 10;
			// var b = 0;
			// ===================================模拟promise错误========================================================
			const f = () => {
				return new Promise((resolve, reject) => {
					setTimeout(() => {
						reject("异步返回信息失败");
					}, 2000);
				});
			};

			f()
				.then(function (res) {
					console.log(res);
				})
				.catch((err) => {
					console.log(err);
					//通过catch捕获之后不会被unhandledrejection捕获，所以要想全局捕获需要手动在抛出异常
					// throw new Error(err);
				});

			// =======================================手动抛出异常=============================================
			// throw new Error("hello");

			try {
				//
				console.log(c);
			} catch (error) {
				console.log("c没有定义");
			} finally {
				//如果手动捕获了异常之后，需要手动抛出才能被全局捕获
				throw new Error(error);
			}
		</script>
	</head>
	<body>
		<!-- 模拟资源加载异常 -->
		<img src="http://192.168.1.123:9090/abc/images/bg_0021.png" />
	</body>
</html>
